packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@swc/core'
  - bigint-buffer
  - blake-hash
  - bufferutil
  - esbuild
  - msw
  - nx
  - protobufjs
  - sharp
  - tiny-secp256k1
  - usb
  - utf-8-validate
  - workerd
