# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: cascade

before:
  hooks:
    - go mod tidy

builds:
  - id: cascade
    main: .
    binary: cascade
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  github:
    owner: cascade-protocol
    name: splits
  name_template: "cascade-cli v{{.Version}}"
  draft: false
  prerelease: auto

brews:
  - name: cascade
    repository:
      owner: cascade-protocol
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://cascade.fyi"
    description: "Cascade CLI - Connect your local MCP server to Cascade Market"
    license: "MIT"
    install: |
      bin.install "cascade"
    test: |
      system "#{bin}/cascade", "--version"

# Note: GoReleaser is deprecating 'brews' in favor of 'homebrew_casks'.
# The 'brews' key still works for CLI tools (non-cask). Monitor for updates.
